import { HS5F_REVERSIBLE_GTR5 } from "./gtr.ts";
import type { PhyloUcaOptions } from "./types.ts";

export function defaultPhyloUcaOptions(): PhyloUcaOptions {
  return {
    characterMode: "auto",
    model: { ...HS5F_REVERSIBLE_GTR5, frequencies: [...HS5F_REVERSIBLE_GTR5.frequencies], exchangeabilities: [...HS5F_REVERSIBLE_GTR5.exchangeabilities] },
    candidates: {
      vMaximumExtraDifferences: 6,
      jMaximumExtraDifferences: 4,
      vMinimumIdentity: 0.82,
      jMinimumIdentity: 0.75,
      maximumVCandidates: 48,
      maximumJCandidates: 24,
      retainObservedHypotheses: true,
    },
    hmm: {
      maximumDSegments: 3,
      minimumDMatch: 5,
      initialDProbability: 0.934,
      additionalDProbability: 0.00125,
      junctionNProbability: 0.973,
      vThreePrimeTrimContinuation: 0.7527,
      dFivePrimeTrimContinuation: 0.8574,
      dThreePrimeTrimContinuation: 0.8471,
      jFivePrimeTrimContinuation: 0.8708,
      meanNLength: 8.8,
      singleNProbability: 0.027,
      nLengthPhases: 2,
      junctionSearchFlankColumns: 16,
      templateMismatchProbability: 0,
      junctionGapProbability: 0.015,
      terminalPaddingGapProbability: 0.01,
      nBaseFrequencies: [0.203, 0.288, 0.304, 0.205],
    },
    search: {
      inferenceMode: "gibbs-mh",
      screenMode: "vj-mixture",
      screenEdgeGridPoints: 5,
      fullHmmEdges: 6,
      edgeGridPoints: 3,
      branchGridPoints: 13,
      minimumPositiveUcaBranchLength: 0.00001,
      maximumUcaBranchLength: 0.3,
      branchPriorMean: 0.06,
      mlOptimizationRounds: 2,
      mlOptimizationTolerance: 0.002,
      localRefinementRounds: 2,
      marginalizeLocally: true,
      localPosteriorPoints: 12,
      edgePrior: "uniform-length",
      mcmcIterations: 320,
      mcmcBurnIn: 80,
      mcmcThin: 2,
      mcmcMhStepsPerIteration: 4,
      mcmcBranchProposalScale: 0.012,
      mcmcPositionProposalScale: 0.4,
      mcmcGlobalJumpProbability: 0.12,
      mcmcGlobalPositionMixture: 0.85,
      mcmcGlobalPositionScale: 0.18,
      mcmcGlobalBranchMixture: 0.9,
      mcmcGlobalBranchMaximum: 0.03,
      mcmcCollapsedInitializerMixture: 0.95,
      mcmcCollapsedRefreshInterval: 3,
      mcmcSeed: 1729,
    },
  };
}
