import {useState} from 'react';
import type {UnifiedDashboard} from './unified-germline';
export function UnifiedGermlineResultsPanel({dashboard,name}:{dashboard:UnifiedDashboard;name:string}){
 const [showAll,setShowAll]=useState(false);
 const rows=dashboard.results.flatMap(g=>g.evidence.map(e=>({...e,component:g.key,train:g.trainingLineages,test:g.testLineages,frequency:g.theta[e.candidate],threshold:Math.log(Math.max(1,dashboard.evidenceRule.testsBySubject[g.key.split("|")[0]])/dashboard.evidenceRule.alpha)}))).sort((a,b)=>(b.logEvidence??-Infinity)-(a.logEvidence??-Infinity));
 const download=()=>{const blob=new Blob([JSON.stringify(dashboard,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${name}.joint-inherited-shm.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="analysis-extension-results"><header className="extension-result-heading"><div><span className="section-kicker">Separate experimental result</span><h3>Joint inherited / SHM evidence</h3><p>{rows.filter(r=>r.logEvidence>=r.threshold).length} of {rows.length} proposed sequences pass the model-conditional evidence rule; {rows.filter(r=>r.logEvidence>0).length} have positive evidence. Neither count establishes biological truth.</p></div><button type="button" onClick={download}>Download complete evidence JSON</button></header>
 {dashboard.warnings.map(w=><p key={w}>{w}</p>)}
 <label><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/> Show all tested proposals, including unsupported hypotheses</label>
 <div className="lineage-table-wrap"><table><thead><tr><th>Subject / component</th><th>Proposed sequence</th><th>Training / test lineages</th><th>Training inherited fraction</th><th>Held-out log evidence</th><th>Model-conditional rule</th><th>Null optimization bound gap</th></tr></thead><tbody>{rows.filter(r=>showAll||r.logEvidence>0).map(r=><tr key={r.component+r.sequence}><td>{r.component}</td><td><code>{r.id}</code><small>Final two bases unresolved</small></td><td>{r.train} / {r.test}</td><td>{(r.frequency*100).toFixed(2)}%</td><td>{r.logEvidence==null||!Number.isFinite(r.logEvidence)?'Not supported':r.logEvidence.toFixed(3)}</td><td>{r.logEvidence>=r.threshold?"Pass":"Below rule"}<small>Required log evidence {r.threshold.toFixed(2)}</small></td><td>{r.gap==null?'—':r.gap.toFixed(3)}</td></tr>)}</tbody></table></div>
 <p>Evidence compares a training-fitted alternative against an upper bound on the best held-out null, allowing the proposed sequence as a somatic outcome. Negative evidence is lack of support, not proof of genomic absence. These results do not modify the other method or current assignments.</p>
 </section>;
}
